# Configurações do Banco de Dados
DB_HOST = "localhost"
DB_NAME = "athlete_monitoring"
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_PORT = 5432

# Chave secreta para JWT
SECRET_KEY = "seu_secret_key_super_secreto_aqui"

# Outras configurações
ENVIRONMENT = "development"
